//
//  KindDeckModel.swift
//  TheKind
//
//  Created by Tenny on 2/25/19.
//  Copyright © 2019 tenny. All rights reserved.
//

import Foundation


enum KindCardId: Int {
    case angel = 1,
    trailblazer = 2,
    entertainer = 3,
    leader = 4,
    grinder = 5,
    idealist = 6,
    teamplayer = 7,
    visionary = 8,
    founder = 9,
    explorer = 10,
    mentor = 11,
    rebel = 12,
    agnostic = 13,
    believer = 14,
    guided = 15,
    simulation = 16,
    onelikethesky = 17,
    aequanimus = 18,
    keeper = 19,
    nomad = 20,
    servant = 21,
    blindfolded = 22,
    original = 23,
    player = 24,
    bonvivant = 25,
    achiever = 26,
    director = 27,
    controller = 28,
    enthusiast = 29,
    optmistic = 30,
    empathetic = 31,
    poet = 32,
    still = 33,
    connector = 34,
    shapeshifter = 35,
    ingenius = 36,
    artist = 37,
    realist = 38,
    ally = 39,
    champion = 40,
    perfectionist = 41,
    juggler = 42,
    adventurer = 43,
    jumper = 44,
    seeker = 45,
    traditionalist = 46,
    modernist = 47,
    moderator = 48
}

enum KindName: String {
    case angel = "The Angel",
    trailblazer = "The Trailblazer",
    entertainer = "The Entertainer",
    leader = "The Leader",
    grinder = "The Grinder",
    idealist = "The Idealist",
    teamplayer = "The Team Player",
    visionary = "The Visionary",
    founder = "The Founder",
    explorer = "The Explorer",
    mentor = "The Mentor",
    rebel = "The rebel",
    agnostic = "The Agnostic",
    believer = "The Believer",
    guided = "The Guided",
    simulation = "The Simulation",
    onelikethesky = "The One Like The Sky",
    aequanimus = "The Aequanimus",
    keeper = "The Keeper",
    nomad = "The Nomad",
    servant = "The Servant",
    blindfolded = "The Blindfolded",
    original = "The Original",
    player = "The Player",
    bonvivant = "The Bon Vivant",
    achiever = "The Achiever",
    director = "The Director",
    controller = "The Controller",
    enthusiast = "The Enthusiast",
    optmistic = "The Optmistic",
    empathetic = "The Empathetic",
    poet = "The Poet",
    still = "The Still",
    connector = "The Connector",
    shapeshifter = "The Shapeshifter",
    ingenius = "The Ingenius",
    artist = "The Artist",
    realist = "The Realist",
    ally = "The Ally",
    champion = "The Champion",
    perfectionist = "The Perfectionist",
    juggler = "The Juggler",
    adventurer =  "The Adventurer",
    jumper = "The Jumper",
    seeker = "The Seeker",
    traditionalist = "The Traditionalist",
    modernist = "The Modernist",
    moderator = "The Moderator"
}
