# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheKind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!

  # Pods for TheKind

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'NVActivityIndicatorView'
pod 'AWSRekognition'
pod 'Mapbox-iOS-SDK', '4.8.0-alpha.2'
pod 'Koloda'

  target 'TheKindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheKindUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
